import scrapy


class AdItem(scrapy.Item):
    title = scrapy.Field()
    price = scrapy.Field()
    currency = scrapy.Field()
    location = scrapy.Field()
    description = scrapy.Field()
    seller_name = scrapy.Field()
    phone = scrapy.Field()
    images = scrapy.Field()
    posted_date = scrapy.Field()
    category = scrapy.Field()
    condition = scrapy.Field()
    specs = scrapy.Field()
    ad_url = scrapy.Field()
    source = scrapy.Field()
    price_eur = scrapy.Field()
    price_mkd = scrapy.Field()
    price_note = scrapy.Field()
    scraped_at = scrapy.Field()
    seller_notes = scrapy.Field()
    seller_type = scrapy.Field()
    delivery_available = scrapy.Field()
    llm_parsed_at = scrapy.Field()
