-- =====================================================================
-- 001 Нормализација на шемата
--
-- * шифрарници: sources, categories, locations, brands, models, clusters
-- * ads   = што е објавено на порталот (го пишуваат spider-ите)
-- * ad_analysis (1 : 1 со ads) = што заклучиле агентите за огласот:
--   тип, бренд, модел, кластер, клучно инфо, сооднос со новата цена ...
-- * models ги чува двете „нови“ цени на моделот: пазарната (медијана од
--   огласите за нов уред) и LLM-проценката (досега model_price_estimates);
--   анализата на огласот чува само reference_source, т.е. која од двете
--   важи за него (новите огласи не се споредуваат со пазарот)
-- * цената станува износ + валута, а price_mkd е генерирана колона
-- * duplicates добива вистински надворешни клучеви кон ads
-- * ads_view ги спојува табелите назад во „рамен“ облик за читање
--
-- Старите колони во ads (текстуалните source, category, location, brand,
-- model, cluster_label, reference_*, price, price_eur, price_note и
-- колоните што се преселуваат во ad_analysis) и табелата
-- model_price_estimates НЕ се бришат тука, туку во 002, откако ќе се
-- провери дека ништо не е изгубено.
-- =====================================================================

set statement_timeout = 0;
begin;

-- 0. Табели што повеќе не се користат (двете се во резервната копија):
--    price_history е празен остаток од стариот Celery прототип,
--    retail_prices ги чуваше цените од Setec, кој е пензиониран.
drop table if exists public.price_history;
drop table if exists public.retail_prices;


-- 1. Шифрарници -------------------------------------------------------

create table public.sources (
    source_id integer generated by default as identity primary key,
    name      text not null unique,
    base_url  text
);

create table public.categories (
    category_id integer generated by default as identity primary key,
    source_id   integer not null references public.sources (source_id),
    name        text    not null,
    unique (source_id, name)
);

create table public.locations (
    location_id integer generated by default as identity primary key,
    name        text not null unique
);

create table public.brands (
    brand_id integer generated by default as identity primary key,
    name     text not null
);
-- „HP“ и „Hp“ се ист бренд
create unique index brands_name_lower_key on public.brands (lower(name));

create table public.models (
    model_id                integer generated by default as identity primary key,
    brand_id                integer not null references public.brands (brand_id),
    name                    text    not null,
    market_new_price_mkd    numeric,   -- медијана од огласите за нов уред
    market_sample_size      integer,   -- од колку такви огласи
    estimated_new_price_mkd numeric,   -- LLM-проценка
    estimated_at            timestamptz
);
create unique index models_brand_name_lower_key on public.models (brand_id, lower(name));

-- cluster_id го доделува Clustering Agent (KMeans), затоа не е identity.
create table public.clusters (
    cluster_id integer primary key,
    label      text
);


-- 2. Пополнување на шифрарниците од постојните огласи -------------------

-- 89 огласи од pazar3 се внесени од помошен spider без source; изворот се
-- чита од самото URL.
update public.ads set source = 'pazar3'
where nullif(trim(source), '') is null and ad_url like '%pazar3.mk/%';
update public.ads set source = 'reklama5'
where nullif(trim(source), '') is null and ad_url like '%reklama5.mk/%';

insert into public.sources (name)
select distinct source from public.ads where nullif(trim(source), '') is not null;

update public.sources set base_url = 'https://www.pazar3.mk' where name = 'pazar3';
update public.sources set base_url = 'https://reklama5.mk'   where name = 'reklama5';

insert into public.categories (source_id, name)
select distinct s.source_id, trim(a.category)
from public.ads a
join public.sources s on s.name = a.source
where nullif(trim(a.category), '') is not null;

insert into public.locations (name)
select distinct trim(location) from public.ads where nullif(trim(location), '') is not null;

-- За секој бренд се зема најчестото пишување („HP“, а не „Hp“).
insert into public.brands (name)
select distinct on (lower(trim(brand))) trim(brand)
from public.ads
where nullif(trim(brand), '') is not null
group by trim(brand)
order by lower(trim(brand)), count(*) desc, trim(brand);

-- Брендови што постојат само во кешот на проценки (без оглас).
insert into public.brands (name)
select distinct on (lower(trim(e.brand))) trim(e.brand)
from public.model_price_estimates e
where nullif(trim(e.brand), '') is not null
  and not exists (select 1 from public.brands b where lower(b.name) = lower(trim(e.brand)))
order by lower(trim(e.brand)), trim(e.brand);

insert into public.models (brand_id, name)
select distinct on (b.brand_id, lower(trim(a.model))) b.brand_id, trim(a.model)
from public.ads a
join public.brands b on lower(b.name) = lower(trim(a.brand))
where nullif(trim(a.model), '') is not null
group by b.brand_id, trim(a.model)
order by b.brand_id, lower(trim(a.model)), count(*) desc, trim(a.model);

-- Модели што постојат само во кешот на проценки (без оглас).
insert into public.models (brand_id, name)
select distinct on (b.brand_id, lower(trim(e.model))) b.brand_id, trim(e.model)
from public.model_price_estimates e
join public.brands b on lower(b.name) = lower(trim(e.brand))
where nullif(trim(e.model), '') is not null
  and not exists (
      select 1 from public.models m
      where m.brand_id = b.brand_id and lower(m.name) = lower(trim(e.model)))
order by b.brand_id, lower(trim(e.model)), trim(e.model);

-- Проценета нова цена (LLM кеш) -> models
update public.models m
set estimated_new_price_mkd = e.estimated_new_price_mkd,
    estimated_at            = e.estimated_at
from public.model_price_estimates e
join public.brands b on lower(b.name) = lower(trim(e.brand))
where m.brand_id = b.brand_id
  and lower(m.name) = lower(trim(e.model));

-- Пазарна нова цена -> models (медијаната што Reference Price Agent ја
-- пресметал за моделот). Кај 9 модели огласите имаат различни вредности од
-- постари извршувања; се зема онаа од последно скрапираниот оглас, а агентот
-- ја пресметува одново при следното извршување.
update public.models m
set market_new_price_mkd = r.reference_new_price_mkd,
    market_sample_size   = r.reference_sample_size
from (
    select distinct on (b.brand_id, lower(trim(a.model)))
           b.brand_id, lower(trim(a.model)) as model_lower,
           a.reference_new_price_mkd, a.reference_sample_size
    from public.ads a
    join public.brands b on lower(b.name) = lower(trim(a.brand))
    where a.reference_source = 'marketplace'
      and a.reference_new_price_mkd is not null
      and nullif(trim(a.model), '') is not null
    order by b.brand_id, lower(trim(a.model)), a.scraped_at desc nulls last
) r
where m.brand_id = r.brand_id
  and lower(m.name) = r.model_lower;

-- Кластери: само од производите (кај нив етикетите се конзистентни).
insert into public.clusters (cluster_id, label)
select distinct on (cluster_id) cluster_id, cluster_label
from public.ads
where cluster_id is not null and ad_type = 'product'
group by cluster_id, cluster_label
order by cluster_id, count(*) desc;


-- 3. ads: надворешни клучеви и цена -------------------------------------

alter table public.ads
    add column source_id    integer references public.sources (source_id),
    add column category_id  integer references public.categories (category_id),
    add column location_id  integer references public.locations (location_id),
    add column price_amount numeric;

update public.ads a set source_id = s.source_id
from public.sources s where s.name = a.source;

update public.ads a set category_id = c.category_id
from public.categories c
where c.source_id = a.source_id and c.name = trim(a.category);

update public.ads a set location_id = l.location_id
from public.locations l where l.name = trim(a.location);

-- Оригиналниот износ во валутата на огласот. price_mkd/price_eur веќе се
-- бројно парсирани од текстот, па износот се зема од соодветната од нив.
update public.ads
set price_amount = case currency
                       when 'EUR' then price_eur
                       when 'MKD' then price_mkd
                   end
where currency in ('EUR', 'MKD');

-- 4.477 огласи (скрапирани 09.07–20.09) имаат валута и оригинален износ,
-- но пресметаните price_eur/price_mkd им се избришани: парсерот запишуваше
-- во пакети каде полињата за цена ги имаше само кај огласите со поправена
-- цена, па кај другите во истиот пакет стануваа NULL. Износот се враќа од
-- оригиналниот текст.
update public.ads
set price_amount = price::numeric
where price_amount is null
  and currency in ('EUR', 'MKD')
  and price ~ '^[0-9]+(\.[0-9]+)?$';

-- Неколку десетици се во суров облик („4.500 МКД“, „350 €“): македонски
-- формат, точка за илјадници и запирка за децимали, исто како normalize.py.
update public.ads
set price_amount = replace(
        regexp_replace(substring(price from '^[0-9.,[:space:]]+'), '[.[:space:]]', '', 'g'),
        ',', '.')::numeric
where price_amount is null
  and currency in ('EUR', 'MKD')
  and price ~ '^[0-9]';

-- Бројна цена без запишана валута: пресметана е во денари.
update public.ads
set price_amount = price_mkd, currency = 'MKD'
where currency is null and price_mkd is not null;

alter table public.ads
    add constraint ads_currency_check check (currency in ('MKD', 'EUR'));

-- price_mkd станува генерирана колона: базата сама ја пресметува од
-- износот и валутата (фиксен курс 61.5, како во normalize.py), па никогаш
-- не може да се разликува од оригиналот.
alter table public.ads drop column price_mkd;
alter table public.ads
    add column price_mkd numeric
    generated always as (
        case currency
            when 'MKD' then price_amount
            when 'EUR' then round(price_amount * 61.5, 2)
        end
    ) stored;


-- 4. ad_analysis: резултатите од агентите (1 : 1 со ads) ----------------

create table public.ad_analysis (
    ad_url             text primary key references public.ads (ad_url) on delete cascade,
    ad_type            text,
    is_electronics     boolean,
    brand_id           integer references public.brands (brand_id),
    model_id           integer references public.models (model_id),
    cluster_id         integer references public.clusters (cluster_id) on delete set null,
    seller_notes       text,
    phone              text,
    delivery_available boolean default false,
    reference_source   text check (reference_source in ('marketplace', 'llm_estimate')),
    price_vs_new_ratio numeric,
    good_price_deal    boolean,
    llm_parsed_at      timestamptz
);

insert into public.ad_analysis (
    ad_url, ad_type, is_electronics, brand_id, model_id, cluster_id,
    seller_notes, phone, delivery_available,
    reference_source, price_vs_new_ratio, good_price_deal, llm_parsed_at)
select
    a.ad_url,
    a.ad_type,
    a.is_electronics,
    b.brand_id,
    m.model_id,
    -- огласите што подоцна станаа услуга или „барам“ чуваа стар кластер;
    -- тие не се кластерираат, па остануваат без кластер
    case when a.ad_type = 'product' then k.cluster_id end,
    a.seller_notes,
    a.phone,
    a.delivery_available,
    -- 1.370 огласи сè уште се споредени со Setec, кој е пензиониран: тие
    -- споредби не се пренесуваат (агентот ги пресметува одново)
    case when a.reference_source <> 'setec' then a.reference_source end,
    case when a.reference_source <> 'setec' then a.price_vs_new_ratio end,
    case when a.reference_source = 'setec' then false else a.good_price_deal end,
    a.llm_parsed_at
from public.ads a
left join public.brands   b on lower(b.name) = lower(trim(a.brand))
left join public.models   m on m.brand_id = b.brand_id and lower(m.name) = lower(trim(a.model))
left join public.clusters k on k.cluster_id = a.cluster_id;


-- 5. Вистински надворешни клучеви за duplicates -------------------------

-- Парови чиј оглас веќе не постои во ads (не може да се прикажат).
delete from public.duplicates d
where not exists (select 1 from public.ads a where a.ad_url = d.ad_url_1)
   or not exists (select 1 from public.ads a where a.ad_url = d.ad_url_2);

alter table public.duplicates
    add constraint duplicates_ad_url_1_fkey
        foreign key (ad_url_1) references public.ads (ad_url) on delete cascade,
    add constraint duplicates_ad_url_2_fkey
        foreign key (ad_url_2) references public.ads (ad_url) on delete cascade;


-- 6. Индекси ------------------------------------------------------------

create index idx_ads_source_id_ad_url on public.ads (source_id, ad_url);
create index idx_ads_category_id      on public.ads (category_id);
create index idx_ads_location_id      on public.ads (location_id);
create index idx_ads_price_mkd        on public.ads (price_mkd);
-- Редоследот на листата во апликацијата (најнови прво): страницата се чита
-- директно по индексот и застанува по 20 огласи, наместо да ги сортира сите
-- (локално: 107 наместо 9.015 прочитани блокови).
create index idx_ads_listing_order    on public.ads (posted_date desc nulls last, scraped_at desc);
create index idx_models_brand_id      on public.models (brand_id);
create index idx_duplicates_ad_url_2  on public.duplicates (ad_url_2);

create index idx_ad_analysis_brand_id   on public.ad_analysis (brand_id);
create index idx_ad_analysis_model_id   on public.ad_analysis (model_id);
create index idx_ad_analysis_cluster_id on public.ad_analysis (cluster_id);
create index idx_ad_analysis_ad_type    on public.ad_analysis (ad_type);

-- Делумни индекси за backfill задачите (старите врз текстуалните колони
-- се бришат заедно со колоните во 002).
create index idx_ads_null_category_v2 on public.ads (source_id, ad_url) where category_id is null;
create index idx_ads_null_listing_type_v2 on public.ads (source_id, ad_url) where listing_type is null;
create index idx_ads_null_posted_date_v2 on public.ads (source_id, ad_url) where posted_date is null;
create index idx_ad_analysis_null_brand on public.ad_analysis (ad_url)
    where brand_id is null and llm_parsed_at is not null;
create index idx_ad_analysis_null_is_electronics on public.ad_analysis (ad_url) where is_electronics is null;


-- 7. Поглед за читање ---------------------------------------------------
-- API-то и фронтендот читаат од ads_view, во истиот рамен облик како
-- досега, додека запишувањето оди во нормализираните табели.
-- LEFT JOIN насекаде: PostgreSQL ги прескокнува спојувањата чии колони не
-- се бараат (на пр. при броење), а оглас без анализа сепак се прикажува.

create view public.ads_view with (security_invoker = true) as
select
    a.ad_url,
    s.name               as source,
    a.title,
    a.description,
    a.price_amount,
    a.currency,
    a.price_mkd,
    round(a.price_mkd / 61.5, 2) as price_eur,
    c.name               as category,
    l.name               as location,
    a.images,
    a.seller_name,
    a.seller_type,
    a.posted_date,
    a.listing_type,
    a.condition,
    a.specs,
    a.scraped_at,
    a.created_at,
    a.is_active,
    aa.ad_type,
    aa.is_electronics,
    b.name               as brand,
    m.name               as model,
    aa.seller_notes,
    aa.phone,
    aa.delivery_available,
    aa.cluster_id,
    k.label              as cluster_label,
    -- која од двете цени на моделот важи за огласот, го кажува reference_source
    case aa.reference_source
        when 'marketplace'  then m.market_new_price_mkd
        when 'llm_estimate' then m.estimated_new_price_mkd
    end                  as reference_new_price_mkd,
    case aa.reference_source
        when 'marketplace'  then m.market_sample_size
        when 'llm_estimate' then 1
    end                  as reference_sample_size,
    aa.reference_source,
    aa.price_vs_new_ratio,
    aa.good_price_deal,
    aa.llm_parsed_at,
    a.source_id,
    a.category_id,
    a.location_id,
    aa.brand_id,
    aa.model_id
from public.ads a
left join public.sources     s  on s.source_id   = a.source_id
left join public.categories  c  on c.category_id = a.category_id
left join public.locations   l  on l.location_id = a.location_id
left join public.ad_analysis aa on aa.ad_url     = a.ad_url
left join public.brands      b  on b.brand_id    = aa.brand_id
left join public.models      m  on m.model_id    = aa.model_id
left join public.clusters    k  on k.cluster_id  = aa.cluster_id;


-- 8. Функцијата што ја чита Orchestrator Agent ---------------------------

create or replace function public.pipeline_status()
returns table(total bigint, classified bigint, products bigint, services bigint, wanted bigint,
              parsed bigint, clustered bigint, referenced bigint, duplicate_pairs bigint, estimated bigint)
language sql stable
as $$
    select
        a.total, a.classified, a.products, a.services, a.wanted,
        a.parsed, a.clustered, a.referenced,
        (select count(*) from public.duplicates) as duplicate_pairs,
        (select count(*) from public.models where estimated_new_price_mkd is not null) as estimated
    from (
        select
            count(*)                                                 as total,
            count(*) filter (where aa.ad_type is not null)           as classified,
            count(*) filter (where aa.ad_type = 'product')           as products,
            count(*) filter (where aa.ad_type = 'service')           as services,
            count(*) filter (where aa.ad_type = 'wanted')            as wanted,
            count(*) filter (where aa.llm_parsed_at is not null)     as parsed,
            count(*) filter (where aa.cluster_id is not null)        as clustered,
            count(*) filter (where aa.price_vs_new_ratio is not null) as referenced
        from public.ads a
        left join public.ad_analysis aa on aa.ad_url = a.ad_url
    ) a;
$$;

-- Бројките за страничната лента на апликацијата (/api/ads/stats) во едно
-- барање, наместо 8 одделни броења кои повремено паѓаа со statement timeout.
-- Ист филтер како листата: исклучени се само огласите потврдени дека не се
-- електроника (is_electronics = false).
create or replace function public.ad_stats()
returns json
language sql stable
as $$
    select json_build_object(
        'total',   count(*) filter (where e),
        'sources', json_build_object(
            'pazar3',   count(*) filter (where e and s.name = 'pazar3'),
            'reklama5', count(*) filter (where e and s.name = 'reklama5')),
        'duplicates', (select count(*) from public.duplicates),
        'good_deals', count(*) filter (where aa.good_price_deal),
        'ad_types', json_build_object(
            'product', count(*) filter (where e and aa.ad_type = 'product'),
            'service', count(*) filter (where e and aa.ad_type = 'service'),
            'wanted',  count(*) filter (where e and aa.ad_type = 'wanted')))
    from public.ads a
    left join public.sources s on s.source_id = a.source_id
    left join public.ad_analysis aa on aa.ad_url = a.ad_url
    cross join lateral (select aa.is_electronics is distinct from false as e) f;
$$;

-- Најчестите 40 категории со број на огласи (/api/ads/categories). Иста
-- ознака може да постои на двата портала, па се групира по име. Досега API-то
-- ги поминуваше сите огласи на страници од по 1.000 при секое вчитување.
create or replace function public.category_counts()
returns table(name text, count bigint)
language sql stable
as $$
    select c.name, count(*)
    from public.ads a
    join public.categories c on c.category_id = a.category_id
    group by c.name
    order by count(*) desc
    limit 40;
$$;

commit;

-- По миграцијата (надвор од трансакцијата, VACUUM не може во неа) скриптата
-- пушта:  vacuum analyze public.ads;
-- за да се исчистат старите верзии на редовите од UPDATE-ите и да се
-- освежат статистиките што ги користи планерот на барања.
