// The parser stores spec keys in English ("storage", "battery_health") so
// they stay consistent across ads; this turns them into Macedonian labels
// for display. Unknown keys are shown as written, tidied up.
const KEY_LABELS = {
  storage: 'Меморија',
  memory: 'Меморија',
  rom: 'Меморија',
  capacity: 'Капацитет',
  ram: 'RAM',
  processor: 'Процесор',
  cpu: 'Процесор',
  cores: 'Јадра',
  threads: 'Нишки',
  'clock speed': 'Брзина на процесорот',
  cache: 'Кеш',
  socket: 'Сокет',
  display: 'Екран',
  screen: 'Екран',
  'screen size': 'Големина на екранот',
  size: 'Големина',
  resolution: 'Резолуција',
  'refresh rate': 'Освежување',
  'response time': 'Време на одзив',
  panel: 'Панел',
  'panel type': 'Тип на панел',
  'display type': 'Тип на екран',
  brightness: 'Осветленост',
  monitor: 'Монитор',
  battery: 'Батерија',
  'battery health': 'Состојба на батеријата',
  'cycle count': 'Циклуси на полнење',
  charging: 'Полнење',
  'charging time': 'Време на полнење',
  charger: 'Полнач',
  gpu: 'Графичка картичка',
  graphics: 'Графичка картичка',
  'graphics card': 'Графичка картичка',
  vga: 'Графичка картичка',
  vram: 'Видео меморија',
  video: 'Видео',
  motherboard: 'Матична плоча',
  mb: 'Матична плоча',
  case: 'Кутија',
  psu: 'Напојување',
  'power supply': 'Напојување',
  power: 'Моќност',
  voltage: 'Напон',
  current: 'Струја',
  cooling: 'Ладење',
  cooler: 'Ладилник',
  'cpu cooler': 'Ладилник за процесорот',
  fans: 'Вентилатори',
  ssd: 'SSD',
  hdd: 'HDD',
  disk: 'Диск',
  'optical drive': 'Оптички уред',
  odd: 'Оптички уред',
  'read speed': 'Брзина на читање',
  os: 'Оперативен систем',
  'operating system': 'Оперативен систем',
  software: 'Софтвер',
  model: 'Модел',
  brand: 'Бренд',
  type: 'Тип',
  version: 'Верзија',
  generation: 'Генерација',
  year: 'Година',
  color: 'Боја',
  colour: 'Боја',
  material: 'Материјал',
  dimensions: 'Димензии',
  weight: 'Тежина',
  'form factor': 'Форма',
  camera: 'Камера',
  'front camera': 'Предна камера',
  'rear camera': 'Задна камера',
  sensor: 'Сензор',
  stabilization: 'Стабилизација',
  keyboard: 'Тастатура',
  mouse: 'Глувче',
  ports: 'Приклучоци',
  connector: 'Приклучок',
  interface: 'Интерфејс',
  connectivity: 'Поврзување',
  connection: 'Поврзување',
  network: 'Мрежа',
  'bluetooth version': 'Bluetooth верзија',
  audio: 'Звук',
  speakers: 'Звучници',
  microphone: 'Микрофон',
  'frequency response': 'Фреквентен опсег',
  frequency: 'Фреквенција',
  impedance: 'Импеданса',
  sensitivity: 'Чувствителност',
  speed: 'Брзина',
  compatibility: 'Компатибилност',
  accessories: 'Додатоци',
  features: 'Карактеристики',
  controller: 'Контролер',
  controllers: 'Контролери',
  games: 'Игри',
  cables: 'Кабли',
  jailbreak: 'Чипуван',
  warranty: 'Гаранција',
  condition: 'Состојба',
  format: 'Формат',
  mileage: 'Километража',
  engine: 'Мотор',
}

const VALUE_LABELS = {
  yes: 'да',
  true: 'да',
  no: 'не',
  false: 'не',
  included: 'вклучени',
  none: 'нема',
  'n/a': 'нема',
  good: 'добра',
  'very good': 'многу добра',
  excellent: 'одлична',
  original: 'оригинал',
  black: 'црна',
  white: 'бела',
  silver: 'сребрена',
  gray: 'сива',
  grey: 'сива',
  blue: 'сина',
  red: 'црвена',
  green: 'зелена',
  gold: 'златна',
  pink: 'розова',
  purple: 'виолетова',
}

function normalize(text) {
  return String(text).trim().toLowerCase().replace(/[_-]+/g, ' ').replace(/\s+/g, ' ')
}

export function specLabel(key) {
  const label = KEY_LABELS[normalize(key)]
  if (label) return label
  const tidy = String(key).replace(/_/g, ' ').trim()
  return tidy.charAt(0).toUpperCase() + tidy.slice(1)
}

export function specValue(value) {
  return VALUE_LABELS[normalize(value)] ?? value
}
